name: Deploy Application Code

on:  # Trigger this workflow manually
  workflow_dispatch:
    inputs:
      application:
        description: 'Application Workload'
        required: true
        default: 'record-store'
      application_repo:
        description: 'Repository with Application Code'
        required: true
        default: 'MaryKroustali/record_store_app'
      application_repo_folder:
        description: 'Folder with Application Code'
        required: true
        default: 'WebApplication8/'

permissions:
  id-token: write

jobs:
  deploy_app_code:
    name: Deploy Application Source Code to WebApp
    runs-on: self-hosted
    steps:
      - name: "Checkout Application repository"
        uses: actions/checkout@main
        with:
          repository: ${{ inputs.application_repo }}
          path: record_store_app      
      - name: "Login to Azure"
        uses: azure/login@v2
        with:
          # Set secrets value as described in https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure-openid-connect#prerequisites
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        env:
          PATH: C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Users\vmadmin\AppData\Local\Microsoft\WindowsApps;
      - name: "Deploy application code in Azure webapp"
        uses: azure/webapps-deploy@v3
        with: 
          app-name: app-${{ inputs.application }}
          package: record_store_app/${{ inputs.application_repo_folder }}
